### PR TITLE
BLD: Correct MKL path for Windows

### PR DESCRIPTION
**Pull request by carterbox**
The file structure on Windows is different for anaconda. Things are 
located in a Library directory instead of relative to the CONDA_PREFIX. 
This commit also replaces two get_filename_components with a with 
grabbing the CONDA_PREFIX environment variable.

### CODE REVIEW

**Comment by carterbox** [comment]
This doesn't fix the Windows build because of the problem where MSVC has it's own special complex type, but I wanted to push it so you were aware of the `CONDA_PREFIX` env variable. I couldn't think of a reason why you would want to use the two calls to `get_filename_components` instead of using `CONDA_PREFIX` directly.

The Linux build still works with this change on my computer.

**Comment by jrmadsen** [comment]
I would say this should be an addition instead of a replacement -- replacing could cause a problem because `export PATH=/path/to/conda/bin:${PATH}` would enable using conda but doesn't set `CONDA_PREFIX` -- so there would be an issue if in the `base` env. Also, we can check for directories, such as `if(EXISTS "$ENV{CONDA_PREFIX}" AND IS_DIRECTORY "$ENV{CONDA_PREFIX}")`

**Comment by jrmadsen** [comment]
Actually, for Windows, the `Library` path-suffix for Windows is probably better off added to `PATH_SUFFIXES` in the `FIND_PATH(MKL_ROOT_DIR ...)`. I will look at the folder structure later because I haven't perused the folder structure on Windows

**Comment by carterbox** [comment]
You mean something like this?
```cmake
if(PYTHON_EXECUTABLE)
        if(EXISTS "$ENV{CONDA_PREFIX}" AND IS_DIRECTORY "$ENV{CONDA_PREFIX}")
            set(_MKL_PREFIX $ENV{CONDA_PREFIX})
        else()
             # platform specific relative path trickery from the python binary 
```

**Comment by jrmadsen** [comment]
Not exactly. IMO, there shouldn't be exclusive dependence on an environment variable bc it is not cached like the value of python executable. Also, precedence should be given to the root directory of the python executable since python is *required* for tomopy but conda is just the *recommended* way to install the package.

**Comment by carterbox** [comment]
I think what you mean is that `_MKL_PREFIX` is one directory up from the python executable because you assume that:
1. The filesystem is organized in a standard unix way
2. MKL is installed to the same prefix as `PYTHON_EXECUTABLE`

```
/foo
  /bin/PYTHON_EXECUTABLE
  /lib  # mkl is here
  /include  # mkl is here
```
That makes sense for Unix. However, Anaconda Windows uses the following file structure.
```
/CONDA_PREFIX
  /PYTHON_EXECUTABLE
  /Library
    /include  # mkl is here
    /lib  # mkl is here
```
All of TomoPy Windows developers I know use Anaconda, so here is my new proposal.

```cmake
if(PYTHON_EXECUTABLE)
    if(WIN32)
        if(EXISTS "$ENV{CONDA_PREFIX}" AND IS_DIRECTORY "$ENV{CONDA_PREFIX}")
            set(_MKL_PREFIX $ENV{CONDA_PREFIX})
        else()
            # complain that Windows user isn't using anaconda prompt
    else(WIN32)
      # unix relative path trickery from the python binary 
```

**Comment by jrmadsen** [comment]
So I re-ran the build in AppVeyor to verify I didn't miss tomopy failing on Windows. I am seeing this:

```
-- Found PythonInterp: C:/Miniconda35-x64/python.exe (found version "3.5.5") 
-- Found MKL: C:/Miniconda35-x64/Library (found version "2018.0.3") found components:  rt
```
and
```
-- Found PythonInterp: C:/Miniconda36-x64/python.exe (found version "3.6.6") 
-- Found MKL: C:/Miniconda36-x64/Library (found version "2018.0.3") found components:  rt 
```

indicating there is not a problem with the current setup so why exactly are you trying to change this?

This should be sufficient:
```
    if(PYTHON_EXECUTABLE)
        get_filename_component(_MKL_PREFIX ${PYTHON_EXECUTABLE} DIRECTORY)
        if(UNIX)
            get_filename_component(_MKL_PREFIX ${_MKL_PREFIX} DIRECTORY)
        endif()
        list(APPEND CMAKE_PREFIX_PATH
            ${_MKL_PREFIX} # common path for UNIX
            ${_MKL_PREFIX}/Library # common path for Windows
            $ENV{CONDA_PREFIX} # fallback if set
        )
    endif()
```

**Comment by jrmadsen** [comment]
I am always hesitant to change things that work without there being an actual problem and am extremely hesitant to change something that works generically to something that relies on a specific setup, such as using Anaconda and CONDA_PREFIX being set. Standard CMake does not extensively rely on environment settings. I don't even make the assumption that TomoPy is built via `setup.py <command>`! You can create a separate build directory and run CMake directly, build, test, and install from there and never touch `setup.py`.

Appending to `CMAKE_PREFIX_PATH` is not an assumption about where MKL exists, it is just a recommendation about where to look and helps ensure that the MKL found in the Python tree is a higher priority than a system MKL.

**Comment by carterbox** [comment]
At the time that I originally opened this pull request, you had not pushed a build system that was capable of finding MKL. I was continuing to offer ideas because I was not aware that you had already fixed the problem on your own branch. Apparently, you fixed it, so this pull is obsolete.

**Comment by jrmadsen** [comment]
Well I just pushed these updates (along with others I hadn't pushed yet) based on your information about the folder structure of MKL on Windows but the AppVeyor logs on Windows before this commit indicated that it was finding MKL:
```
-- Found MKL: C:/Miniconda35-x64/Library (found version "2018.0.3") found components:  rt
```
so I had never looked into it. Was it failing locally for you or something then?

**Comment by carterbox** [comment]
I did fail locally for me, but apparently not for the reason that I created this pull request. I don't know why I opened this pull.... :man_shrugging: Sorry for the red-herring.

**Pull request closed without merging**
